spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
  messages:
    basename: messages, validate

server:
  port: 8081
  servlet:
    context-path: /base-rest-api
