spring:
  application:
    name: AUTH-SERVICE

# Items that apply to ALL profiles:
eureka:
  instance:
    appname: AUTH-SERVICE  # ==> This is a instance of AUTH-SERVICE
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://my-eureka-server.com:9000/eureka

server:
  port: 9100