spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true

server:
  port: 8082
  servlet:
    context-path: /kitcut
#  context-path: /kitcut

language: en